name: InvChest
version: '${project.version}'
main: cn.craftime.invchest.InvChest
authors: [OutHimic、TTOCServer]
description: 让容器里的物品自己流进玩家的口袋。启普发生器更新
website: github.com/TTOCServer/
api-version: 1.13
commands:
  invchest:
    description: InvChest main command
    aliases: [ic]
    usage: /invchest <bind|unbind|list|start|stop|abind|aunbind|alist|astart|astop|reload>
    permission: invchest.bind
permissions:
  invchest.bind:
    description: Allows a player to bind/unbind containers
    default: true
  invchest.statue:
    description: Allows a player to start/stop transfers
    default: true
  invchest.abind:
    description: Allows admin bind/unbind/list for others
    default: op
  invchest.astatue:
    description: Allows admin start/stop for others or global
    default: op
  invchest.inf:
    description: Shows owner info in protected message
    default: op
  invchest.reload:
    description: Allows reloading the plugin configuration
    default: op
